spring:
  application:
    name: spring-boot-lesson-3
    services:
      IssueService:
        maxAllowedBooks: 5
  datasource:
    url: jdbc:postgresql://localhost:5432/mylibrarydb
    username: librarian
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true